DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample9",
    "number": "519-580-7654"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample8",
    "number": "519-580-7654"
}